# Generated by Django 3.1 on 2020-10-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Measurement', models.CharField(max_length=10)),
                ('Drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.drink')),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.ingredient')),
            ],
            options={
                'unique_together': {('Drink', 'Ingredient')},
            },
        ),
    ]
