# Generated by Django 3.1 on 2020-10-13 04:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_drink_datestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='Datestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drink',
            name='Name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message="Name must be alphanumeric and may contain only: ./#'-.", regex="^[a-zA-Z0-9 /#'-\\.]+$")]),
        ),
        migrations.AlterField(
            model_name='drink',
            name='Type',
            field=models.CharField(choices=[('Beer', 'Beer'), ('Cocktail', 'Cocktail'), ('Cocoa', 'Cocoa'), ('Coffee/Tea', 'Coffee/Tea'), ('Homemade Liqueur', 'Homemade Liqueur'), ('Milk/Float/Shake', 'Milk/Float/Shake'), ('Ordinary Drink', 'Ordinary Drink'), ('Other/Unknown', 'Other/Unknown'), ('Punch/Party Drink', 'Punch/Party Drink'), ('Shot', 'Shot'), ('Soft Drink/Soda', 'Soft Drink/Soda')], max_length=20, validators=[django.core.validators.RegexValidator(message='Name must be alphanumeric and may also contain dashes.', regex='^[a-zA-Z /]+$')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='Name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message="Name must be alphanumeric and may contain only: ./#'-.", regex="^[a-zA-Z0-9 /#'-\\.]+$")]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Measurement',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Measurement must be alphanumeric and may \n                           contain only spaces, periods and dashes.', regex='^[a-zA-Z -\\.]+$')]),
        ),
    ]
